### ISSUE TITLE
enable to find where to put data

### ISSUE THREAD

**Issue by kaminek** [tinoji/rundeck-huginn-plugin#1]
Hi,
I'm trying to use this plugin since the builtin Webhook plugin doesn't support data in `json` format, can you explain how it works ?

**Comment by tinoji** [comment]
Hi!
This plugin just sends JSON instead of XML to Webhook URL.  The documentation of the builtin notification plugin for XML is: https://docs.rundeck.com/docs/manual/notifications/webhooks.html

README explains installation and configurations. Please check it.

**Comment by kaminek** [comment]
thx a lot.
