### ISSUE TITLE
Send to multiple URLs

### ISSUE THREAD

**Issue by tinoji** [tinoji/rundeck-huginn-plugin#3]
@cturla
I watched good enhancements in your fork! 👍 
https://github.com/cturla/rundeck-json-webhook-plugin

If there are no problems, I wanna merge your commits. Would you send pull request?

**Comment by cturla** [comment]
@tinoji yeah sure, but I got one more improvement to do, which is to properly handle socket connection and read timeout. After that, I'll open a PR.

**Comment by tinoji** [comment]
@cturla 
I got it! I'll be waiting for your PR! :raised_hands:

**Comment by cturla** [comment]
@tinoji 
here's the pull request #4
